name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    concurrency:
      group: test-${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:

      - name: Checkout project
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Test
        run: |
          chmod +x shell.sh
          ./shell.sh travis
